
"""
Migration: Remove season_id from Player, ensure Schedule.season_id is used for season association.
Revision ID: remove_season_id_from_player
Revises: add_player_and_game_type
Create Date: 2025-07-23
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'remove_season_id_from_player'
down_revision = 'add_player_and_game_type'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player') as batch_op:
        batch_op.drop_constraint('player_season_id_fkey', type_='foreignkey')
        batch_op.drop_column('season_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player') as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('player_season_id_fkey', 'season', ['season_id'], ['id'])
    # ### end Alembic commands ###
